### ISSUE TITLE
Publication used on VAD

### ISSUE THREAD

**Issue by Murmelmaus** [Zhangtingyuxuan/voice_activity_detection#1]
Hello there!

I am testing different Methods for VAD for my master thesis an I was wondering, is there a paper on wich your VAD is based. I am especially interested in the computation of energy_high and energy_low. You write something like "e_low_multifactor = 1.0 is the usual" so I would like to ask where from do you have this information and the formulas to compute the zero_crossing_rate and short_time_energy.
I will be very gratefull for your reply. Thanks in advance.
Best regards,
Adriana

**Comment by zlzhang1124** [comment]
Hi Adriana!

Sorry for my late reply.
Usually, According to the definition of short-time energy and zero-crossing rate, the calculation formula of them can be obtained easily on the Internet. The commonly used VAD technique is the dual-threshold endpoint detection based on short-time energy and zero-crossing rate. 
Audio endpoint detection is to detect valid speech segments from continuous speech streams. It includes two aspects: the beginning point of the detected valid speech is the front endpoint, and the endpoint of the detected valid speech is the back endpoint. If the energy value of the first consecutive M0 frames of the audio is below a pre-specified threshold of energy value E0, and the energy value of the next consecutive M0 frames is greater than E0, the point where the energy value of the speech increases is the front end of the speech. Similarly, if the energy value of successive frames of speech is large and the energy value of subsequent frames is small and lasts for a certain length of time, it can be considered that the place where the energy value decreases is the back endpoint of the speech.
Now the question is, what is the energy threshold E0? What's M0? The ideal mute energy value is 0. Unfortunately, there is often a certain intensity of background sound in the scene where the audio is collected. This pure background sound is silent, of course, but its energy value is obviously not zero. Therefore, the background sound of the actual captured audio usually has a certain basic energy value.
We always assume that there is a small silence at the beginning of the captured audio, usually a few hundred milliseconds long, and this silence is the basis for estimating the threshold E0. It is important to always assume that the little sound at the beginning of the audio is silent! To estimate E0, take a certain number of frames such as the first 100 frames of speech data (these are "muted"), calculate the average energy value, and then add an empirical value or multiply by a coefficient to get E0. This E0 is our benchmark for judging whether a frame is silent or not. Anything above this value is considered to be valid speech, and anything below this value is considered to be silent. As for M0, it is relatively easy to understand because its size determines the sensitivity of endpoint detection. The smaller M0 is, the higher the sensitivity of endpoint detection will be, and vice versa.
So, back to your question. In the code, one-fourth of the mean energy(the short-time energy mean of all frames) is used as the high energy threshold("energy_high"), the energy mean value of the first 5 frames + 1/5 of the "energy_high", and multiply by a factor("e_low_multifactor") is used as the low energy threshold("energy_low"), the mean of zero-crossing rate * zcr_multifactor is used as the threshold of zero-crossing rate("zcr_threshold"). In other words, the above specific parameters are only empirical values based on different application scenarios.
Finally, you can refer to the following publications for the information and formulas to compute the zero-crossing rate and short-time energy.
[1] Zhang, T., Shao, Y., Wu, Y., Geng, Y., Fan, L., 2020. An overview of speech endpoint detection algorithms. Applied Acoustics 160, 107133.. doi:10.1016/j.apacoust.2019.107133.
[2] Qiuyu Guo, Nan Li and Guangrong Ji, "A improved dual-threshold speech endpoint detection algorithm," 2010 The 2nd International Conference on Computer and Automation Engineering (ICCAE), 2010, pp. 123-126, doi: 10.1109/ICCAE.2010.5451414.

Best regards,
ZL. Z

**Comment by Murmelmaus** [comment]
Hello ZL. Z,
Thank you very much for your reply. It is not late at all, since I just came to the part to describe the acoustic features...
Unfortunately I cannot access the publications for free, but I requested one of them. Otherwise I will just go through the code and look in other literature for the formulas. Thank you again for the detailed information. And

Best regards,
Adriana

**Comment by Murmelmaus** [comment]
Hello again,
Now you write "the mean of zero-crossing rate * zcr_multifactor is used as the threshold of zero-crossing rate ("zcr_threshold")". But everywhere I read, the authors say, sounded segments have lower zcr then unvoiced. Why is it then in your code, that segments with zcr > zcr_threshold are being added:
for j in range(len(voiced_sound_added)):
            i_minus_flag = False
            i = voiced_sound_added[j]
            if j % 2 == 1: 
                while i < len(zcr) and zcr[i] >= zcr_threshold: 
                    # für die Nulldurchgangsrate überschreiten, > sum(zcr) / len(zcr)
                    i += 1  # Suche rechts
                wave_detected.append(i)

Should it not be the opposite: zcr[i] <= zcr_threshold?

Best regards,
Adriana

**Comment by zlzhang1124** [comment]
Hi Adriana,

  Let's first explain what VAD is:
  VAD is to accurately determine the starting point and ending point of the voice in a signal containing voice, and to distinguish the voice segment from the non-voice segment. We know that in a speech, there are silent parts and voiced parts. The silent parts include **unvoiced (i.e. muted), noise, and silence** (noise can be attributed to silence). The voiced and unvoiced parts are useful to us, and we need to get them. It can be said that the endpoint detection is to distinguish the two parts. (Note that, just as you said, the unvoiced part belongs to the consonants in the sound, with **low energy and high zero-crossing rate, usually at both ends of the voiced part**.)
  The important thing is, **the energy of voiced sounds is higher than that of unvoiced sounds, and the zero-crossing rate of unvoiced sounds is higher than that of the silent part.** In this case, we can first use energy to distinguish the voiced parts and then use the zero-crossing rate to extract the unvoiced sounds, thus completing the endpoint detection. With regard to using zero-crossing rate to extract the unvoiced sounds, because both ends of the speech part is a consonant (that is, the unvoiced part), is also a part of the speech, but the energy of the consonant and the silent part of the energy is as low, but the zero-crossing rate is much higher than the silent part. In order to distinguish the two, the speech segments that have been distinguished by short-term energy are continued to be searched at both ends. The part with the zero-crossing rate greater than the 'zcr_threshold' is considered as the voice part of the speech. 
  Therefore, in this part of the code, using 'zcr[i] >= zcr_threshold' rather than 'zcr[i] <= zcr_threshold', where the 'zcr_threshold'  used to determine the boundary of unvoiced sounds and distinguish the voice segment from the non-voice segment. 

Best regards,
ZL. Z

**Comment by Murmelmaus** [comment]
Hi ZL. Z,

Thank you very much for your fast reply! 
I see. The double-threshold VAD does not discard high-energy sounds with ZCR higher than the characteristic one for speech. So unvoiced segments with energy high enough to pass the energy threshold could be taken as voiced. That explains what I red in the papers, that double-threshold VAD could have trouble detecting speech in noisy surroundings. There are probably other reasons too, but for me understanding how it works was the essential.
However, it is fast and needs less computational power so I will stick to it in my master thesis.
Thank you again for the provided code here and your time answering my questions!

Best regards,
Adriana
